### ISSUE TITLE
handle voiceover conflicts

### ISSUE THREAD

**Issue by colegleason** [hulop/NavCog#15]
1. Either disable voice over to speak navigation messages that are higher priority
2. Or, wait until voice over is complete and then read from a queue

**Comment by loopRW** [comment]
Currently it uses only voice over and it does not mix self voicing and voice over so it can be considered solved.

The instruction "Previous instruction" is used to read the first instruction at the start. The title of the button, however, is misleading, it should be changed to "Last Instruction".

**Comment by dsato80** [comment]
This issue was moved to hulop/NavCogIOS#17
