### ISSUE TITLE
Reset orientation to account for drift

### ISSUE THREAD

**Issue by colegleason** [hulop/NavCog#6]
While walking on an edge, save orientation data (one sample or average) and get that relative to whatever orientation the edge is.Use this to account for drift.

**Comment by loopRW** [comment]
I am starting to investigate this one

**Comment by loopRW** [comment]
Fixed and in master. I want to try to omit the initialize orientation button completely

**Comment by dsato80** [comment]
This issue was moved to hulop/NavCogIOS#9
